# -*- coding: utf-8 -*-
"""quiz_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBSAomu0o_HDja7scrP-twuyXJ40wjRk
"""

# ============================================
# 🧠 Python Quiz Game Project
# Internship: Upskill Campus x UniConverge Technologies
# Developer: Mayuri
# ============================================

print("🎯 Welcome to the Python Quiz Game Project!")
print("Let's begin by setting up our environment...")

# Import required libraries
import json
import random
import os

# Let's create a JSON file with quiz questions
quiz_data = [
    {
        "question": "What is the capital of France?",
        "options": ["Paris", "Berlin", "Rome", "Madrid"],
        "answer": "Paris"
    },
    {
        "question": "Which programming language is known as the backbone of web development?",
        "options": ["Python", "JavaScript", "C++", "Java"],
        "answer": "JavaScript"
    },
    {
        "question": "Who developed Python?",
        "options": ["Guido van Rossum", "James Gosling", "Dennis Ritchie", "Bjarne Stroustrup"],
        "answer": "Guido van Rossum"
    },
    {
        "question": "Which keyword is used to define a function in Python?",
        "options": ["define", "def", "function", "lambda"],
        "answer": "def"
    }
]

# Save to a JSON file
with open("questions.json", "w") as file:
    json.dump(quiz_data, file, indent=4)

print("✅ Quiz data saved successfully in 'questions.json'")

# Function to load quiz questions from a file
def load_questions(filename="questions.json"):
    try:
        with open(filename, "r") as file:
            questions = json.load(file)
        print(f"✅ {len(questions)} questions loaded successfully!")
        return questions
    except FileNotFoundError:
        print("❌ Error: Question file not found.")
        return []

# Function to display a question and get user's input
def ask_question(question_data):
    print("\n" + question_data["question"])
    for i, option in enumerate(question_data["options"], start=1):
        print(f"{i}. {option}")

    while True:
        try:
            choice = int(input("Enter your answer (1-4): "))
            if 1 <= choice <= len(question_data["options"]):
                return question_data["options"][choice - 1]
            else:
                print("⚠️ Please enter a number between 1 and 4.")
        except ValueError:
            print("⚠️ Invalid input. Please enter a number.")

# Function to run the quiz
def run_quiz(questions):
    print("\n🎯 Welcome to the Python Quiz Game!")
    print("====================================")

    score = 0
    random.shuffle(questions)

    for q in questions:
        user_answer = ask_question(q)
        if user_answer.lower() == q["answer"].lower():
            print("✅ Correct!\n")
            score += 1
        else:
            print(f"❌ Incorrect! The correct answer was: {q['answer']}\n")

    print("====================================")
    print(f"🏆 Quiz Complete! Your Final Score: {score}/{len(questions)}")
    percentage = (score / len(questions)) * 100
    if percentage == 100:
        print("🌟 Excellent! Perfect Score!")
    elif percentage >= 70:
        print("👏 Great job! You did really well!")
    elif percentage >= 50:
        print("🙂 Good effort! Keep practicing.")
    else:
        print("💡 Needs Improvement. Try again!")

# Load questions and start the quiz
questions = load_questions("questions.json")
if questions:
    run_quiz(questions)

# Commented out IPython magic to ensure Python compatibility.
# Save notebook and push to GitHub (optional)
# Replace with your GitHub username, repo name, and email

!git config --global user.name "YourGitHubUsername"
!git config --global user.email "your-email@example.com"

# Clone repo (replace with your repo URL)
!git clone https://github.com/YourGitHubUsername/quiz-game-project.git

# Copy notebook and JSON file
!cp /content/questions.json quiz-game-project/
!cp /content/*.ipynb quiz-game-project/

# Commit and push
# %cd quiz-game-project
!git add .
!git commit -m "Added Quiz Game Colab notebook and data"
!git push

from google.colab import files
files.download("quiz_results.txt")







